# Generated by Django 4.1.7 on 2023-03-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_push', '0002_rename_type_article_classification_article_auther_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
