# Generated by Django 4.1.7 on 2023-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_push', '0003_rename_auther_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(help_text='文章日期，格式为YYYY-MM-DD'),
        ),
    ]
